mode_1:
	g++ -DMODE_1 -Ofast testcase-generator.cpp -o mode_1
mode_2:
	g++ -DMODE_2 -Ofast testcase-generator.cpp -o mode_2
mode_3:
	g++ -DMODE_3 -Ofast testcase-generator.cpp -o mode_3
mode_all:
	g++ -DMODE_3 -Ofast testcase-generator.cpp -o mode_all