name: Dijkstra testing

on:
  push:
    paths:
      - .github/workflows/dijkstra.yml
      - src/*
      - src/**/*
      - test/dijkstra/*
      - check.py

jobs:
  test:
    name: Run Tests
    env:
      DEBUG_SO: "1"
    runs-on: ubuntu-latest
    steps:
      - name: Update Package List and Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Testcases generator
        run: python3 test/dijkstra/generator-pipeline.py

      - name: Run Dijkstra Vector (C++) Test
        run: python3 check.py test/dijkstra/main_vector.cpp test/dijkstra/

      - name: Run Dijkstra Deque (C++) Test
        run: python3 check.py test/dijkstra/main_deque.cpp test/dijkstra/

      - name: Run Dijkstra Brodnik (C++) Test
        run: python3 check.py test/dijkstra/main_brodnik.cpp test/dijkstra/