name: Sort testing

on:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Update Package List and Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Testcases generator
        run: python3 test/liner_search/generator.py

      - name: Run Brodnik (C++) Liner Search Test
        run: python3 check.py test/liner_search/main_brodnik.cpp test/liner_search/

      - name: Run Brodnik (C) Liner Search Test
        run: python3 check.py test/liner_search/main_brodnik.c test/liner_search/ gcc
      
      - name: Run STL Vector (C++) Liner Search Test
        run: python3 check.py test/liner_search/main_vector.cpp test/liner_search/