name: Stack testing

on:
  push:
    paths:
      - .github/workflows/stack.yml
      - src/*
      - test/stack/*
      - check.py

jobs:
  test:
    name: Run Tests
    env:
      DEBUG_SO: "1"
    runs-on: ubuntu-latest
    steps:
      - name: Update Package List and Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install psutil 
        run: pip install psutil

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Testcases generator
        run: python3 test/stack/generator-pipeline.py

      - name: Run Brodnik (C++) Sort Test
        run: python3 check.py test/stack/main_brodnik.cpp test/stack/

      - name: Run Brodnik (C) Sort Test
        run: python3 check.py test/stack/main_brodnik.c test/stack/ gcc
      
      - name: Run STL Stack Deque (C++) Sort Test
        run: python3 check.py test/stack/main_stack_deque.cpp test/stack/
      
      - name: Run STL Stack Vector (C++) Sort Test
        run: python3 check.py test/stack/main_stack_vector.cpp test/stack/
      
      - name: Run STL Stack list (C++) Sort Test
        run: python3 check.py test/stack/main_stack_list.cpp test/stack/