name: Stack testing

on:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Update Package List and Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Testcases generator
        run: python3 test/stack/generator.py

      - name: Run Brodnik (C++) Sort Test
        run: python3 check.py test/stack/main_brodnik.cpp test/stack/

      - name: Run Brodnik (C) Sort Test
        run: python3 check.py test/stack/main_brodnik.c test/stack/ gcc
      
      - name: Run STL Vector (C++) Sort Test
        run: python3 check.py test/stack/main_stack.cpp test/stack/